import React from 'react';
import { Dictionary } from './types';

export const DEFAULT_DICTIONARY: Dictionary = {
    'aba': { jrai: 'Aba', viet: 'Con ba ba' },
    'aban': { jrai: 'Aban', viet: 'Cái chăn' },
    'abih': { jrai: 'Abih', viet: 'Hết' },
    'abih bang': { jrai: 'Abih bang', viet: 'Tất cả, hết thảy' },
    'abih bang ako monuih': { jrai: 'Abih bang akô̌ mơnuih', viet: 'Dân số' },
    'acong': { jrai: 'Ačong', viet: 'Cái cuốc' },
    'adai': { jrai: 'Adai', viet: 'Bầu trời' },
    'adoi': { jrai: 'Adơi', viet: 'Em' },
    'adrang ko-eng': { jrai: 'Adrang kơ-eng', viet: 'Dây thắt lưng' },
    'adring sang': { jrai: 'Adring sang', viet: 'Hiên nhà' },
    'adrung sang': { jrai: 'Adrung sang', viet: 'Trần nhà' },
    'adung': { jrai: 'Adung', viet: 'Mũi' },
    'agaih': { jrai: 'Agaih', viet: 'Sạch' },
    'ai': { jrai: 'Ai', viet: 'Anh rể, chị dâu' },
    'ai hotai': { jrai: 'Ai hơtai', viet: 'Sức lực' },
    'akiang': { jrai: 'Akiăng', viet: 'Cạnh' },
    'ako': { jrai: 'Akô̌', viet: 'Cái đầu' },
    'ako ngok dok u': { jrai: 'Akô̌ ngok đok ư', viet: 'Đồng ý' },
    'aku': { jrai: 'Aku', viet: 'Cái đuôi' },
    'aku tuai': { jrai: 'Aku tuai', viet: 'Cái đuôi khố' },
    'ala': { jrai: 'Ala', viet: 'Đất, con rắn' },
    'alah': { jrai: 'Alah', viet: 'Lười, ngại' },
    'ale': { jrai: 'Ale', viet: 'Cây họ tre (dùng để đan lát)' },
    'ama': { jrai: 'Ama', viet: 'Bố' },
    'amai': { jrai: 'Amai', viet: 'Chị' },
    'amang': { jrai: 'Amăng', viet: 'Trong' },
    'amang bah': { jrai: 'Amăng bah', viet: 'Miệng' },
    'amang krah': { jrai: 'Amăng krah', viet: 'Bên trong' },
    'amang krah ploi': { jrai: 'Amăng krah plơi', viet: 'Trong làng' },
    'amang lam': { jrai: 'Amăng lăm', viet: 'Bên trong' },
    'ami': { jrai: 'Amĭ', viet: 'Mẹ' },
    'ami ba ama ba': { jrai: 'Amĭ ba ama bă', viet: 'Cha sinh mẹ đẻ' },
    'amon': { jrai: 'Amôn', viet: 'Cháu (gọi cô, dì, chú, bác)' },
    'amra': { jrai: 'Amra', viet: 'Sẽ' },
    'amra chim': { jrai: 'Amră', viet: 'Con công' },
    'amun': { jrai: 'Amuñ', viet: 'Dễ, rẻ' },
    'amun bia ma': { jrai: 'Amuñ biă mă', viet: 'Rất rẻ' },
    'amun hluh': { jrai: 'Amuñ hluh', viet: 'Dễ hiểu' },
    'ana': { jrai: 'Ană', viet: 'Con' },
    'ana amon': { jrai: 'Ană amôn', viet: 'Con cháu' },
    'ana aneh': { jrai: 'Ană aneh', viet: 'Con cái' },
    'ana ayong': { jrai: 'Ană ayong', viet: 'Con của anh' },
    'ana ba': { jrai: 'Ană bă', viet: 'Con cái' },
    'ana bloi': { jrai: 'Ană blơi', viet: 'Dân làng' },
    'ana dam': { jrai: 'Ană dam', viet: 'Con trai' },
    'ana drit druai': { jrai: 'Ană drit druai', viet: 'Con mồ côi' },
    'ana kocua': { jrai: 'Ană kơčua', viet: 'Con đầu' },
    'ana monuih': { jrai: 'Ană mơnuih', viet: 'Con người' },
    'ana toco': { jrai: 'Ană tơčô', viet: 'Con cháu' },
    'anai': { jrai: 'Anai', viet: 'Này, đây' },
    'anai po anap': { jrai: 'Anai pơ anap', viet: 'Từ nay về sau' },
    'anam': { jrai: 'Anăm', viet: 'Đừng' },
    'anan': { jrai: 'Anan', viet: 'Tên' },
    'anan iao': { jrai: 'Anan iâo', viet: 'Tên gọi' },
    'anan pan': { jrai: 'Anan pan', viet: 'Tên tuổi' },
    'anap': { jrai: 'Anap', viet: 'Trước (phía trước)' },
    'anet doi': { jrai: 'Anet đơi', viet: 'Bé quá, nhỏ quá' },
    'ang': { jrai: 'Ang', viet: 'Tự cho mình oai, giỏi' },
    'angin': { jrai: 'Angin', viet: 'Gió' },
    'ania': { jrai: 'Ania', viet: 'Nái (heo, bò)' },
    'anih anom': { jrai: 'Anih anom', viet: 'Chỗ ở' },
    'anih hram': { jrai: 'Anih hrăm', viet: 'Lớp học' },
    'anih pit': { jrai: 'Anih pit', viet: 'Phòng ngủ' },
    'anih truh': { jrai: 'Anih truh', viet: 'Địa chỉ người nhận' },
    'anih tuai': { jrai: 'Anih tuai', viet: 'Phòng khách' },
    'anom': { jrai: 'Anom', viet: 'Nơi chốn' },
    'anong': { jrai: 'Anong', viet: 'Cậu' },
    'anu': { jrai: 'Añŭ', viet: 'Dây chuyền' },
    'anun': { jrai: 'Anun', viet: 'Đó' },
    'anun kah': { jrai: 'Anun kah', viet: 'Như vậy mới' },
    'anun yoh': { jrai: 'Anun yơh', viet: 'Vì vậy' },
    'ao': { jrai: 'Ao', viet: 'Áo' },
    'ao podao': { jrai: 'Ao pơđao', viet: 'Áo ấm' },
    'ao bok': { jrai: 'Ao bôk', viet: 'Áo phông' },
    'ao klum': { jrai: 'Ao klum', viet: 'Áo khoác' },
    'apui': { jrai: 'Apui', viet: 'Lửa' },
    'apui arok': { jrai: 'Apui arôk', viet: 'Lửa đuốc' },
    'apui dien': { jrai: 'Apui điên', viet: 'Đèn điện' },
    'apui lik trik': { jrai: 'Apui lik trik', viet: 'Điện' },
    'arang': { jrai: 'Arang', viet: 'Người ta, của' },
    'arat': { jrai: 'Arat', viet: 'Gân' },
    'arat drah': { jrai: 'Arat drah', viet: 'Mạnh máu' },
    'arat jolan': { jrai: 'Arat jơlan', viet: 'Con đường' },
    'arok': { jrai: 'Arôk', viet: 'Đuốc' },
    'asar': { jrai: 'Asar', viet: 'Viên, hạt' },
    'aseh': { jrai: 'Aseh', viet: 'Con ngựa' },
    'asoi': { jrai: 'Asơi', viet: 'Cơm' },
    'at': { jrai: 'At', viet: 'Cũng' },
    'ataih mong': { jrai: 'Ataih mơng', viet: 'Cách xa' },
    'ataih tin': { jrai: 'Ataih tin', viet: 'Xa lắc, xa tít' },
    'atao': { jrai: 'Atâo', viet: 'Con ma' },
    'atur sang': { jrai: 'Atur sang', viet: 'Sàn nhà' },
    'ayat': { jrai: 'Ayăt', viet: 'Giặc' },
    'ayong': { jrai: 'Ayong', viet: 'Anh' },
    'ayun': { jrai: 'Ayun', viet: 'Nhún (nhún nhảy)' },
    'ba': { jrai: 'Ba', viet: 'Mang đi' },
    'ba nao': { jrai: 'Ba nao', viet: 'Dắt đi, dẫn đi' },
    'ba truh': { jrai: 'Ba truh', viet: 'Mang đến, đưa đến' },
    'bah amang': { jrai: 'Bah amăng', viet: 'Cửa lớn' },
    'bai': { jrai: 'Bai', viet: 'Gùi thưa' },
    'bang': { jrai: 'Bang', viet: 'Sáng' },
    'bang yua': { jrai: 'Bang yua', viet: 'Ảnh hưởng' },
    'be': { jrai: 'Bê', viet: 'Con dê' },
    'be cau': { jrai: 'Bĕ', viet: 'Từ dùng đặt cuối câu cầu khiến' },
    'ber': { jrai: 'Ber', viet: 'Thấp, ngắn' },
    'bia ma': { jrai: 'Biă mă', viet: 'Chủ yếu' },
    'bip': { jrai: 'Bip', viet: 'Con vịt' },
    'bla': { jrai: 'Bla', viet: 'Ngà' },
    'blah ayat': { jrai: 'Blah ayăt', viet: 'Đánh giặc' },
    'blah nga': { jrai: 'Blah ngă', viet: 'Chiến đấu' },
    'blan': { jrai: 'Blan', viet: 'Tháng, trăng' },
    'blan không': { jrai: 'Blan không', viet: 'Tháng không mưa' },
    'bloi monia': { jrai: 'Blơi mơnia', viet: 'Mua bán' },
    'bobung sang': { jrai: 'Bơbung sang', viet: 'Mái nhà' },
    'bocolah': { jrai: 'Bơčơlah', viet: 'Chia tay nhau' },
    'bocum': { jrai: 'Bơcŭm', viet: 'Hôn nhau' },
    'boh than': { jrai: 'Bôh than', viet: 'Kết quả' },
    'bohang': { jrai: 'Bơhăng', viet: 'Ớt' },
    'bohnar': { jrai: 'Bơhnar', viet: 'Người Bahnar' },
    'bohor': { jrai: 'Bơhor', viet: 'Thích nhau' },
    'bohram': { jrai: 'Bơhrăm', viet: 'Cùng học' },
    'bokonal': { jrai: 'Bơkơnal', viet: 'So sánh' },
    'bokonar': { jrai: 'Bơkơnar', viet: 'Bình đẳng, công bằng, đều nhau' },
    'bolai': { jrai: 'Bơlăi', viet: 'Thảo luận, bàn bạc' },
    'bomonoi': { jrai: 'Bơmơnơi', viet: 'Cùng tắm' },
    'bonai': { jrai: 'Bơnai', viet: 'Con gái' },
    'bongat': { jrai: 'Bơngat', viet: 'Linh hồn' },
    'bongat jua': { jrai: 'Bơngat jua', viet: 'Tinh thần' },
    'boni popu': { jrai: 'Bơni pơpŭ', viet: 'Phong tặng' },
    'borohlac': { jrai: 'Bơrơhlač', viet: 'Lấp lánh' },
    'boromi': { jrai: 'Bơrơmi', viet: 'Rằm (trăng)' },
    'boromut': { jrai: 'Bơrơmut', viet: 'Ghét' },
    'boronai': { jrai: 'Bơrơñai', viet: 'Bình đẳng' },
    'borotut': { jrai: 'Bơrơtut', viet: 'Lấm chấm (nổi trên mặt nước)' },
    'boroyong': { jrai: 'Bơrơyong', viet: 'Bồng bềnh (mây trôi)' },
    'botaih': { jrai: 'Bơtaih', viet: 'Đánh nhau' },
    'botona': { jrai: 'Bơtơña', viet: 'Hỏi nhau, hỏi thăm' },
    'bra': { jrai: 'Bra', viet: 'Vai' },
    'brah': { jrai: 'Brah', viet: 'Sưng, viêm' },
    'braih': { jrai: 'Braih', viet: 'Gạo' },
    'broi': { jrai: 'Brơi', viet: 'Cho' },
    'brua': { jrai: 'Bruă', viet: 'Việc, nghề nghiệp' },
    'brua hma podai': { jrai: 'Bruă hma pơdai', viet: 'Làm nông' },
    'brua konua': { jrai: 'Bruă kơnuă', viet: 'Công việc' },
    'brua monam': { jrai: 'Bruă mơñam', viet: 'Việc đan lát' },
    'brua monua': { jrai: 'Bruă mơnuă', viet: 'Công việc' },
    'brua potruh nao rai': { jrai: 'Bruă pơtruh nao rai', viet: 'Bưu điện' },
    'brua tohan ling': { jrai: 'Bruă tơhan ling', viet: 'Quân sự' },
    'brua tri trah': { jrai: 'Bruă trĭ trah', viet: 'Nghề mộc' },
    'brua yom phan': { jrai: 'Bruă yô̌m phan', viet: 'Việc quan trọng' },
    'buai': { jrai: 'Buai', viet: 'Bông tai' },
    'buc': { jrai: 'Buč', viet: 'Nhổ' },
    'can': { jrai: 'Čan', viet: 'Vay' },
    'can prak': { jrai: 'Čan prak', viet: 'Vay tiền' },
    'cang': { jrai: 'Čang', viet: 'Trông mong' },
    'cang romang': { jrai: 'Čang rơmang', viet: 'Hy vọng' },
    'cao': { jrai: 'Čâ̆o', viet: 'Bắt đầu' },
    'car': { jrai: 'Čar', viet: 'Tỉnh' },
    'car ako phun': { jrai: 'Čar akô̌ phun', viet: 'Thủ đô' },
    'car rongiao': { jrai: 'Čar rơngiao', viet: 'Nước ngoài' },
    'ceh': { jrai: 'Čeh', viet: 'Nở (con gà nở)' },
    'ceh topai': { jrai: 'Čeh tơpai', viet: 'Cái ghè rượu' },
    'cem': { jrai: 'Čem', viet: 'Cho ăn, đút ăn' },
    'cem nuoi': { jrai: 'Čem', viet: 'Nuôi' },
    'ceo': { jrai: 'Čeo', viet: 'Chèo' },
    'ci': { jrai: 'Či', viet: 'Muốn, sắp (dự định)' },
    'cih hra': { jrai: 'Čih hră', viet: 'Viết thư' },
    'cim brim': { jrai: 'Čim brim', viet: 'Chim chóc' },
    'cing horgor': { jrai: 'Čing hơgor', viet: 'Chiêng trống' },
    'cing sar': { jrai: 'Čing sar', viet: 'Chiêng lễ hội' },
    'co': { jrai: 'Čô', viet: 'Tên (đơn vị người)' },
    'codeh muai': { jrai: 'Čơđeh muai', viet: 'Trẻ em' },
    'codeng': { jrai: 'Čơđeng', viet: 'Ngón tay' },
    'codong': { jrai: 'Čơđông', viet: 'Bẫy' },
    'cogong': { jrai: 'Čơgông', viet: 'Tha đi, mang đi' },
    'coka': { jrai: 'Čơkă', viet: 'Đón' },
    'colah': { jrai: 'Čơlah', viet: 'Chia tay' },
    'colu': { jrai: 'Čơlŭ', viet: 'Cái tô' },
    'cong': { jrai: 'Čong', viet: 'Chặt, cắt' },
    'copan': { jrai: 'Čơpan', viet: '8' },
    'copet': { jrai: 'Čơpet', viet: 'Bóp' },
    'cor sang': { jrai: 'Čôr sang', viet: 'Xà nóc, nóc nhà' },
    'cran': { jrai: 'Čran', viet: 'Đoạn, phần' },
    'crek': { jrai: 'Črek', viet: 'Chẽ ra' },
    'crong': { jrai: 'Črong', viet: 'Chông' },
    'cu': { jrai: 'Čư̆', viet: 'Núi' },
    'cuh': { jrai: 'Čuh', viet: 'Nở' },
    'cuh monŭ': { jrai: 'Čuh mơnŭ', viet: 'Làm thịt gà' },
    'cuh ploi pla': { jrai: 'Čuh plơi pla', viet: 'Đốt làng' },
    'cuh sang': { jrai: 'Čuh sang', viet: 'Đốt nhà' },
    'cum': { jrai: 'Čum', viet: 'Ngửi, hôn' },
    'cut': { jrai: 'Čut', viet: 'Mặc (áo), đeo (vòng)' },
    'da': { jrai: 'Đa', viet: 'Từ dùng cuối câu cầu xin' },
    'da da': { jrai: 'Đa đa', viet: 'Vân vân' },
    'dah bonai': { jrai: 'Đah bơnai', viet: 'Con gái' },
    'dah rokơi': { jrai: 'Đah rơkơi', viet: 'Con trai' },
    'dam': { jrai: 'Dam', viet: 'Nam thanh niên, trai' },
    'dam dra': { jrai: 'Dam dra', viet: 'Thanh niên nam nữ' },
    'dang': { jrai: 'Đang', viet: 'Vườn' },
    'dang wang': { jrai: 'Dang wang', viet: 'Xe đạp' },
    'dao': { jrai: 'Dao', viet: 'Con dao' },
    'dao tin': { jrai: 'Đăo', viet: 'Tin' },
    'dap': { jrai: 'Dap', viet: 'Xếp' },
    'dap glai': { jrai: 'Dap glăi', viet: 'Xếp lại' },
    'deh': { jrai: 'Dêh', viet: 'Châu lục' },
    'deh dam': { jrai: 'Đeh dam', viet: 'Thanh niên' },
    'dhot': { jrai: 'Đhot', viet: 'Tẩu' },
    'di': { jrai: 'Đĭ', viet: 'Lên' },
    'di koyar': { jrai: 'Đĭ kơyar', viet: 'Phát triển' },
    'di rodeh': { jrai: 'Đĭ rơđêh', viet: 'Đi xe' },
    'di trun': { jrai: 'Đĭ trun', viet: 'Lên xuống' },
    'dih': { jrai: 'Dih', viet: 'Kia' },
    'dih pit': { jrai: 'Đih pit', viet: 'Nằm ngủ' },
    'ding': { jrai: 'Đing', viet: 'Ống hút' },
    'ding dao': { jrai: 'Đing đăo', viet: 'Nghi ngờ' },
    'dja': { jrai: 'Djă', viet: 'Cầm, nắm, mang' },
    'dja kojap': { jrai: 'Djă kơjap', viet: 'Nắm chắc' },
    'dja pioh': { jrai: 'Djă piôh', viet: 'Lưu giữ' },
    'djai': { jrai: 'Djai', viet: 'Chết' },
    'djai bru': { jrai: 'Djai brŭ', viet: 'Chết chóc' },
    'djhul': { jrai: 'Djhul', viet: 'Nhẹ' },
    'djo': { jrai: 'Djơ̆', viet: 'Đúng' },
    'djom': { jrai: 'Djom', viet: 'Hiền' },
    'djop': { jrai: 'Djop', viet: 'Đủ, khắp' },
    'djru': { jrai: 'Djru', viet: 'Giúp đỡ' },
    'djung': { jrai: 'Djrưng', viet: 'Cẩn thận' },
    'djuh': { jrai: 'Djuh', viet: 'Củi' },
    'djup': { jrai: 'Djup', viet: 'Hút' },
    'dlai': { jrai: 'Dlai', viet: 'Rừng' },
    'dlai mrok': { jrai: 'Dlai mrok', viet: 'Rừng rậm' },
    'dlai ro-ông': { jrai: 'Dlai rơ-ông', viet: 'Rừng già' },
    'dlang': { jrai: 'Dlăng', viet: 'Xem' },
    'dlang ba': { jrai: 'Dlăng ba', viet: 'Trông coi' },
    'dleh': { jrai: 'Dlêh', viet: 'Mệt, vất vả' },
    'dlong': { jrai: 'Dlông', viet: 'Cao' },
    'dlut': { jrai: 'Dlut', viet: 'Lún, lầy' },
    'do': { jrai: 'Dô̆', viet: 'Ở, còn' },
    'do mo': { jrai: 'Dô̆ mô̌', viet: 'Lấy vợ' },
    'do pluai': { jrai: 'Dô̆ pluai', viet: 'Độc thân' },
    'do todrua': { jrai: 'Dô̆ tơdruă', viet: 'Ở cùng, lấy nhau' },
    'doc': { jrai: 'Đô̌č', viet: 'Chỉ (biểu thị hạn chế)' },
    'doda': { jrai: 'Đơđa', viet: 'Một số, một vài' },
    'dodua': { jrai: 'Dơdua', viet: 'Từng cặp' },
    'doi': { jrai: 'Đơi', viet: 'Quá, lắm' },
    'dok': { jrai: 'Đok', viet: 'Đọc' },
    'dolam': { jrai: 'Dơlam', viet: 'Sâu' },
    'donao': { jrai: 'Dơnao', viet: 'Hồ, ao' },
    'dong': { jrai: 'Dong', viet: 'Đứng, nữa' },
    'dop': { jrai: 'Dop', viet: 'Trộm, cướp' },
    'dor': { jrai: 'Dor', viet: 'Chôn' },
    'dra': { jrai: 'Dra', viet: 'Nữ thanh niên' },
    'drah': { jrai: 'Drah', viet: 'Máu' },
    'drah kotak': { jrai: 'Drah kơtak', viet: 'Xương máu' },
    'drai': { jrai: 'Drai', viet: 'Thác' },
    'dram gonam': { jrai: 'Dram gơnam', viet: 'Đồ đạc' },
    'droi': { jrai: 'Drơi', viet: 'Con (đơn vị con vật)' },
    'dua': { jrai: 'Dua', viet: '2' },
    'duaropan': { jrai: 'Duarơpan', viet: '9' },
    'dui': { jrai: 'Dui', viet: 'Được, sẽ' },
    'dum': { jrai: 'Dum', viet: 'Những, cuối' },
    'eng': { jrai: 'Eng', viet: 'Váy' },
    'eo': { jrai: 'Eo', viet: 'Con mèo' },
    'ga': { jrai: 'Gă', viet: 'Bà' },
    'gac': { jrai: 'Gač', viet: 'Gạch' },
    'gah': { jrai: 'Gah', viet: 'Về (phía)' },
    'gai cih': { jrai: 'Gai čih', viet: 'Bút' },
    'gih': { jrai: 'Gih', viet: 'Các anh, chị' },
    'giong': { jrai: 'Giong', viet: 'Xong' },
    'gong konong': { jrai: 'Gong kơnong', viet: 'Chính quyền' },
    'gong sang': { jrai: 'Gong sang', viet: 'Người trụ cột' },
    'gonong': { jrai: 'Gơnong', viet: 'Cơ quan' },
    'gonu': { jrai: 'Gơñu', viet: 'Chúng nó' },
    'yua hoget': { jrai: 'Yua hơget', viet: 'Vì sao' },
    'yuan': { jrai: 'Yuan', viet: 'Người Kinh' },
    'ya': { jrai: 'Yă', viet: 'Bà nội, ngoại' },
};

export const DiscordIcon = () => (
  <svg className="w-5 h-5 transition-transform group-hover:rotate-12" viewBox="0 0 127.14 96.36" fill="currentColor">
    <path d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.71,32.65-1.82,56.6.48,80.1a105.73,105.73,0,0,0,32.63,16.26,77.7,77.7,0,0,0,7.13-11.59,64.49,64.49,0,0,1-11.35-5.42c.95-.7,1.89-1.42,2.79-2.17a75.56,75.56,0,0,0,64,0c.9.75,1.84,1.47,2.79,2.17a64.58,64.58,0,0,1-11.35,5.42,77.05,77.05,0,0,0,7.13,11.59,105.07,105.07,0,0,0,32.68-16.26c2.72-27.11-4.55-50.87-19.46-72.03ZM42.45,65.69c-6.37,0-11.64-5.84-11.64-13s5.17-13,11.64-13,11.74,5.84,11.64,13S48.92,65.69,42.45,65.69Zm42.24,0c-6.37,0-11.64-5.84-11.64-13s5.17-13,11.64-13,11.74,5.84,11.64,13S84.69,65.69,84.69,65.69Z"/>
  </svg>
);

export const SpeakerIcon = () => (
  <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M11 5L6 9H2v6h4l5 4V5z"></path>
    <path d="M15.54 8.46a5 5 0 0 1 0 7.07" opacity="0.4"></path>
    <path d="M19.07 4.93a10 10 0 0 1 0 14.14"></path>
  </svg>
);